untool/untool

packages/react/mixin.server.js
Setting data.globals in `fetchData` had no effect, because it was always set
to an empty array in `enhanceData`.
=> fix(react): fix data.globals always being overridden

packages/webpack/lib/utils/loader.js
use `default` property if present
=> fix(webpack): make ESM-style runtime mixins work

packages/core/lib/config.js, packages/core/lib/core.js, packages/core/package.json, yarn.lock
This commit adds debug output (via the
[debug package](https://www.npmjs.com/package/debug)).
In order to see the debug output the app needs to be started with the
`DEBUG` environment variable set to `untool:*`.
`$ DEBUG=untool:* un start` will print all debug statements starting
with namespace `untool:`.
This commit introduces two debug namespaces:
- `untool:core`
- `untool:config`
Sample output:
=> RFC: add debug output for config / mixins

packages/core/lib/config.js
Imo devDependencies should also be used to resolve presets.
For example, we are currently building a development proxy that is only needed for development. https://github.com/xing/hops/pull/522
jest-preset could be(come) another example.
Otherwise, you would either have to install devDependencies as dependencies or specify the presets manually.
=> fix(core): take devDependencies into account when resolving presets

packages/react/mixin.browser.js, packages/react/mixin.server.js, packages/webpack/lib/middleware/render.js, packages/webpack/lib/shims/browser.js, packages/webpack/lib/shims/node.js, packages/webpack/mixin.core.js
In order to use tree-shaking features, the entry point needs to be in
ESM format.
This PR rewrites the browser entry point to use ESM and also uses deep
imports to react-router-dom in order to not bundle the whole of
react-router.
=> [RFC]: Enable possible support for tree-shaking untool/hops applications

packages/webpack/lib/plugins/stats.js
The compilation hook "additionalAssets" will be called multiple times
if there are "childCompiler"s present.
In order to prevent this behavior and only emit the "statsFile" for the
compilation object of the parent compiler, we need to filter out
compilations of other compilers which might be present.
=> fix(webpack): emit stats file only for parent compilation

packages/core/lib/config.js
Otherwise it breaks with `TypeError: Cannot destructure property `configNamespace` of 'undefined' or 'null'.`
=> fix(core): allow calling getConfig without arguments

packages/express/lib/run.js
The `getPort(port)` function only accepts a single parameter
=> fix(express): pass correct port parameter to getPort function

packages/webpack/lib/configs/build.js, packages/webpack/lib/configs/develop.js, packages/webpack/lib/configs/node.js, packages/webpack/mixins/config/mixin.core.js
This change allows us to call `this.getBuildConfig('my-build', 'node')`
which will return a webpack config based on the node config and will
call `configureBuild(webpackConfig, loaderConfigs, 'my-build')` with
`target` set to `my-build`, so that the custom webpack config can be
configured via `configureBuild` too.
=> fix(webpack): use target as name for getBuildConfig

packages/react/mixins/mixin.browser.js
HTML5 is pretty forgiving in what it allows to be in an id
However, not everything can be queried using CSS selectors
`document.querySelector(@package/myName)` will produce an error
`document.querySelector(#package.myName)` will not query for `[id="package.myName"]` but for an element with id `package` and class `myName`
=> fix(react): avoid special chars causing issues with React mountpoint

packages/core/README.md, packages/react/lib/render.js, packages/react/mixins/mixin.core.js, packages/react/mixins/mixin.server.js
We decided to strongly discourage adding non-hook methods to mixins as doing so may result in namespace clashes. In this PR, I added appropriate documentation and refactored `@untool/react`'s server mixin to make sure we ourselves adhere to this new best practice.
=> Remove non-hook mixin methods from `@untool/react`

packages/webpack/lib/utils/loader.js
We noticed that running "placeholdify" etc on the config is extremely
costly and at the moment we were executing it on every request.
With this change we will only re-evaluate the config whenever
"overrides" are actually used (most of the times it is just an empty
object).
We measured reqs/sec and on my machine (with hops-template-react), we
got on average:
- before: ~1700 reqs/sec
- after: ~2100 reqs/sec
Co-authored-by: Robin Drexler <drexler.robin@gmail.com>
=> perf(webpack): only re-evaluate config when overrides exist

packages/webpack/lib/plugins/stats.js
Please see [my comment](https://github.com/untool/untool/pull/236/files/5dc4a09451f93f029f303e11967c0b1a41ca8fbf#r244835805) in #236.
=> refactor(webpack): use `compiler.isChild()`

packages/react/lib/template.js
@ZauberNerd:
> In case `fragments` is not defined or an empty object we should ensure that we don't render `undefined` in the template.
> This change adds `|| ''` and sets a default value of an empty object for `fragments`, so we will always render strings only.
=> Fix template

packages/webpack/lib/plugins/stats.js
When you `import` a component (or import a file that exports said component, even if you do not directly use that export), that you also import via `importComponent`, that component will end up in an entry or vendor bundle and thus not be available in the moduleFileMap.
Which causes the following error, when a page is loaded:
```
TypeError: moduleFileMap[module] is not iterable
```
You can reproduce this by going to `master` branch and placing:
```js
import { About as a } from './components/about';
```
in https://github.com/untool/untool/blob/master/tests/fixtures/untest/index.js#L6
This PR fixes the error by ignoring those modules.
I've also added a warning in dev, because this is a situation a user certainly does not want.
Maybe we even want to throw an actual error and don't let users …
=> fix(react): do not error when importComponent module not found

packages/express/lib/serve.js
This is relevant in the `final` phase middleware handlers, that are assigned to the Express app itself and might handle errors. Those error handlers are detected by Express by checking the amount of parameters the function takes. This information is lost, when the middleware is bound to the `domain`.
=> fix(express): keep length property of middleware handlers

packages/core/lib/config.js, packages/core/lib/resolver.js, packages/webpack/preset.js
Architecturally, this change makes `@untool/core` more extensible and prevents it from knowing anything about the browser/server distinction implemented using webpack.
Practically, this allows users to introduce custom mixin types (for example to implement extensible service worker presets) and thus build more advanced extensions.
=> feat(core): make mixin types configurable

.travis.yml, package.json, yarn.lock
This commit adds the "canarist" tool which will clone Hops into a
temporary folder and execute its test suite against the current untool
build.
=> chore: add canarist to run the Hops test suite against current branch

packages/react/README.md, packages/react/lib/babel.js, packages/react/lib/runtime.js, tests/fixtures/untest/index.js
https://astexplorer.net/#/gist/8aa47f0a6619cf54e99bdf60055bf7d0/b4e7efb45ce31269459f1ae67ed9b50d0e812802
In addition to
```js
importComponent('./foo')
```
also allow 
```js
importComponent(() => import('./foo'))
```
This will allow editors to resolve the imported component. In its current form, for editors it's just a string that they can't follow.
=> feat(react): allow import load function in importComponent

packages/react/lib/babel.js
In compiled tests we want to use the `importComponent` feature but we need to set `this.state.Component` synchronously. For this we can provide a mock of `importComponent` in Hops but we need the absolute path to the requested component.
This commit adds an option to the babel plugin to allow to switch `require.resolveWeak` to `require.resolve` which can be used in babel-jest test setups.
=> feat(react): allow to instruct babel plugin to use require.resolve

packages/react/lib/babel.js
Because it opened the plugin for uses cases it is not meant to be used for.
=> refactor(react): remove `resolveAbsolutePaths` option

packages/react/lib/runtime.js, packages/react/mixins/mixin.browser.js, packages/react/mixins/mixin.server.js, tests/fixtures/untest/index.js
Our fixture breaks with the newest version of React Router (v4.4.0) due to this statement:
https://github.com/untool/untool/blob/1621634bdac34f377af23d11c67c0fbb11d04f31/tests/fixtures/untest/index.js#L3
The relevant change was apparently introduced around React Router [v4.4.0-beta2](https://github.com/ReactTraining/react-router/releases/tag/v4.4.0-beta.2). Additionally, warnings are emitted for our other deep imports from React Router, e.g.:
https://github.com/untool/untool/blob/1621634bdac34f377af23d11c67c0fbb11d04f31/packages/react/lib/runtime.js#L5
This PR addresses these issues
=> fix(react): switch to supported react router imports

packages/info/lib/logger.js
Currently, if started in debug mode, `untool` breaks due to our logger being inspected..:
```text
$ DEBUG=untool* yarn start
[...]
untest:info running 'start' in 'development' mode
untest:error TypeError: Cannot convert a Symbol value to a string
at Logger._ (./packages/info/lib/logger.js:53:40)
at formatValue (internal/util/inspect.js:522:31)
at formatProperty (internal/util/inspect.js:1248:11)
at formatRaw (internal/util/inspect.js:771:9)
at formatValue (internal/util/inspect.js:540:10)
at formatProperty (internal/util/inspect.js:1248:11)
at formatArray (internal/util/inspect.js:1076:17)
at formatRaw (internal/util/inspect.js:768:14)
at formatValue (internal/util/inspect.js:540:10)
at formatProperty (internal/util/inspect.js:1248:11)
```
With this PR, we make sure `Logger` instances can …
=> fix(info): make sure logger can be `util.inspect`ed

packages/core/index.js
`args.slice(-1)` would return an array containing the last element of
the args rest, but an array fails the `isPlainObject()` test, therefore
`this.options` would always be set to an empty object, even if
`core.initialize(overrides, { production: true })` was called with an
options object as its second argument.
=> fix(core): take last Mixin constructor arg as options object

packages/webpack/lib/utils/loader.js
With a recent change in untool we now can not generate loaders for
environments other than `browser` or `server`, because we load `utils`
from the `@untool/core` main file which already loads `./lib/config` and
therefore the `browser` config loader will always pass in all browser
mixins.
This commit partially reverts that change by importing the config utils
from `@untool/core/lib/utils` instead.
This is helpful for other compilers, for example the service-worker
compiler in Hops, to allow the service worker bundle to be very small
and not include React and other runtime dependencies.
Ref: https://github.com/untool/untool/commit/4b6352f239a04b223501381e4e9364e4dadb5607
=> fix(webpack): keep config loader small by reducing dependencies

package.json, packages/core/index.js, packages/core/lib/utils.js, packages/core/package.json, packages/express/lib/serve.js, packages/express/mixins/mixin.core.js, packages/express/package.json, packages/react/lib/runtime.js, packages/react/mixins/mixin.browser.js, packages/react/package.json, packages/webpack/mixins/config/mixin.core.js, packages/webpack/mixins/stats/mixin.core.js, packages/webpack/package.json, packages/yargs/mixins/mixin.core.js, packages/yargs/package.json, tests/helpers/normalize.js, yarn.lock
Since [`is-plain-object`](https://github.com/jonschlinkert/is-plain-object/compare/2.0.4...v3.0.0) introduced a ESM style entry point in v3, we need to replace it with something we can uniformly `require`, regardless if the code in question is being transpiled or not: [`is-plain-obj`](https://github.com/sindresorhus/is-plain-obj)
closes #342
=> Replace is-plain-object with is-plain-obj

packages/webpack/lib/configs/develop.js
untool does not allow to start the development server in production mode
and therefore it makes no sense to check for production mode in the
webpack develop config.
=> refactor(webpack): remove obsolete "isProduction" check from dev config

packages/webpack/mixins/stats/mixin.core.js
This is an alternate take on #357 - it attempts to solve the underlying issue without having to extend our API in somewhat unpleasant ways. I have come to think that it is indeed fine for this mixin to evaluate CLI args (and commands) its sibling mixins own/define and to react accordingly. I only prefer it doing to in the appropriate hook.
The implementation I am proposing ought to also be in line with #355, specifically with https://github.com/untool/untool/pull/355/commits/c704683854260dc8fcc2303e134bfe6e82f9ff7f.
Closes #357
=> refactor(webpack): move arg handling to appropriate hook

packages/webpack/lib/shims/develop.js, packages/webpack/package.json, yarn.lock
As a preparation for the webpack 5 release, because webpack 5 doe not
include the Node.js core module polyfills anymore and the `eventsource`
packages has a lot of dependencies to Node core modules which results
in quite a big browser bundle.
=> refactor(webpack): switch to event-source-polyfill for IE11

packages/react/mixins/mixin.server.js
Recently `is-plain-object` has been replaced by `is-plain-obj` in untool
unfortunately one call site was missing and therefore still tried to
load `is-plain-object`.
This PR changes that call site to require `is-plain-obj`.
Ref: https://github.com/untool/untool/commit/a96af55f89437959a879d903eb356bee625bd2f5
=> fix(react): use is-plain-obj instead of is-plain-object

packages/core/lib/utils.js
In #428 we tried to change the merging behaviour for mixins but also change the behaviour for other arrays. The result was that arrays in the config did not override the previous value.
This PR reverts the other change so that the result is:
```diff
-        return [...objValue, ...srcValue];
+        return [...objValue, ...srcValue].filter(
+          (curr, index, self) => self.indexOf(curr) === index
+        );
```
=> fix(core): arrays in config should override previous value

packages/express/package.json, yarn.lock
Portfinder introduced a bug in a previous version that would assign a
random port, even though the basePort option has been set.
=> fix: upgrade portfinder to 1.0.23

packages/info/package.json, packages/webpack/package.json
We use these packages here:
https://github.com/untool/untool/blob/1c7a73909ff08d9e91f0a90618bf65b0aaaafc78/packages/info/lib/logger.js#L7
And here:
https://github.com/untool/untool/blob/1c7a73909ff08d9e91f0a90618bf65b0aaaafc78/packages/webpack/lib/plugins/render.js#L3
=> fix: add missing dependencies

.github/workflows/rebase.yml, scripts/rebase.sh
This action will run on every push to the master branch and rebase the
next branch against master.
If the rebase fails it will check if it is fixable (ie. only conflicts
in "yarn.lock" and/or "tests/snapshots/" and then execute
"yarn install" and "yarn test -u" to fix those conflicts and continue
to rebase.
=> chore: set-up GH action to automatically rebase next branch

packages/webpack/lib/configs/build.js, packages/webpack/lib/configs/develop.js, packages/webpack/lib/configs/node.js
Apparently v8 changed how regular expressions are serialized (v8 got updated between Node.js v12.10.0 and v12.11.0), which causes our snapshot tests to fail.
This change escapes the forward slash in the character group, which isn't exactly necessary (which is also why eslint complaints) but it works across all versions.
=> refactor(webpack): escape forward slashes in regular expressions

packages/core/__tests__/fixtures/a-mixin.js, packages/core/__tests__/fixtures/another-mixin.js, packages/core/__tests__/fixtures/test-mixin.js, packages/core/__tests__/index.test.js
This should check the different mixin options from untool initialize.
=> test: add core initialize test cases

packages/webpack/package.json, yarn.lock
...in order to maintain support for Node LTS 8.10
=> fix(webpack): downgrade url-loader to v2

packages/webpack/package.json, yarn.lock
in order to make sure to get a newer `serialize-javascript` version.
=> fix: upgrade terser-webpack-plugin to latest version

packages/react/mixins/mixin.browser.js
We should wait with unmounting and setting of the `data-mounted` attribute until after the `fetchData` call.
This fix would allow us to wait in our browser tests for the `data-mounted` attribute in order to make sure to have all event handlers bound.
I wonder why this was never an issue before.
=> fix(react): set data-mounted attribute after hydration
