packages/webpack/lib/middleware/assets.js
Same issue as in https://github.com/xing/hops/pull/466
=> fix(webpack): prevent hmr chunks from being inserted into the template

packages/core/lib/config.js
only catch the one relevant error, pass everything else
=> refactor(core): improve preset loading

packages/core/lib/config.js, tests/fixtures/instrument/package.json
If no presets are explicitly configured, find installed presets amongst direct dependencies.
=> Autodetect presets

packages/core/lib/config.js
Co-authored-by: dmbch <daniel@dmbch.net>
=> fix(core): catch resolve errors when searching for presets

packages/core/lib/config.js
=> fix(core): fix placeholdify implementation

package.json, yarn.lock
Allows #100 to be merged eventually.
=> chore: remove @commitlint/config-lerna-scopes

packages/core/lib/config.js
This will allow us to stop relying on `process.env.UNTOOL_NSP`.
=> feat(core): make config namespace configurable

packages/webpack/lib/utils/resolvable.js
Reloading the page currently does not work in dev as soon as a change is made to a file.
=> Revert "refactor(webpack): simplify resolvable"

packages/dist/README.md, packages/react/README.md, packages/react/lib/babel.js, packages/react/lib/runtime.js, tests/fixtures/untest/index.js
Following up on https://github.com/xing/hops/pull/726#discussion_r238790196
=> Rename Import() to importComponent()

packages/webpack/lib/plugins/render.js
This should™ resolve xing/hops/issues/761.
=> fix(webpack): ignore child-compilers in RenderPlugin

README.md, packages/express/README.md, packages/webpack/README.md, packages/yargs/README.md
In this PR, I documented the approach to semver handling discussed for both `untool` and `hops` today IRL. Please let me know if I got it right.
=> Document semver handling

.travis.yml
=> ci: only run canarist build in lts node

packages/webpack/lib/shims/browser.js
Fixes [bug report comment](https://github.com/untool/untool/pull/276/files/af61ddd5079592ceb3a17cd3ef69726f3b4d13a4#r263415570).
Thanks, @Xiphe!
=> fix(webpack): make validation work after hmr

packages/express/package.json
=> chore(express): remove obsolete dependency

packages/webpack/lib/utils/compiler.js
Executing the bootstrap hook in the forked child process sets up the
doctor mixin to run the diagnose hook for all mixins and print out the
diagnose warnings multiple times (for each sub process).
By skipping the bootstrap hook in the child process, the doctor will
never be called and we won't get the same warnings multiple times.
=> fix(webpack): skip bootstrap in child process to skip doctor checks

package.json
=> chore: prevent renovate from pinning versions

packages/webpack/package.json, yarn.lock
This reverts commit 6b114586eee775d234dee978384137cc1c8a4580.
=> fix(webpack): revert #416 (core-js upgrade)

packages/core/__tests__/fixtures/config-mixin.js, packages/core/__tests__/index.test.js
Testing the replacement of placeholders and environment in
the untool configuration.
=> test: test for placeholder and environment config

packages/core/__tests__/fixtures/validate-mixin.js, packages/core/__tests__/index.test.js
This test includes the validate strategie decorator test case for
the success and the error cases.
=> test: add validate decorator test case

packages/react/README.md
=> fix: error in readme

package.json, packages/react/package.json, packages/webpack/package.json, yarn.lock
This is a preparation for https://github.com/xing/hops/pull/969
=> update babel packages to v7.7

.travis.yml
For reference: https://github.com/xing/hops/pull/1023
=> Align travis configs

packages/core/README.md, packages/core/lib/loader.js
=> fix(core): allow to ignore certain presets through "ignoredPresets"
